server:
  port: 8006
spring:
  application:
    name: consul-provider-order
  cloud:
    consul:
      host: localhost
      prot: 8500
      discovery:
        service-name: ${spring.application.name}

